aep/urls.py
# Robin Kalia
# robinkalia@berkeley.edu
# UC Berkeley
#
# Urls.py: Root Url that includes the various urls of all apps in the main project - 'aep'

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^aep/survey/', include('survey.urls', namespace='survey')),
    url(r'^aep/admin/', include(admin.site.urls)),
]

survey/urls.py
# Robin Kalia
# robinkalia@berkeley.edu
# UC Berkeley
#
# Urls.py: Urls used in the 'Survey' Web Application


from django.conf.urls import url

from survey import views

urlpatterns = [
	# Manual Views
	# url(r'^$', views.index, name='index'),
	# url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	# url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
	# Generic Views
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

survey/models.py
# Robin Kalia
# robinkalia@berkeley.edu
# UC Berkeley
#
# models.py: Models defined for the 'Survey' Web App


from django.db import models

import datetime
from django.utils import timezone


class Question(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('Published Date')
	
	def __unicode__(self):
		return self.question
		
	def contains_nonempty_text(self):
		return self.question != ''		
		
	def contains_verylong_text(self):
		text_str = self.question	
		return len(text_str) > 200		

	def posted_shortly(self):
		now = timezone.now() 
		return now - datetime.timedelta(days=1) <= self.pub_date <= now 

	posted_shortly.admin_order_field = 'pub_date'
	posted_shortly.boolean = True
	posted_shortly.short_decription = 'Published recently?'


class Choice(models.Model):
	question = models.ForeignKey(Question)	
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	
	def __unicode__(self):
		return self.choice_text
		
	def contains_nonempty_text(self):
		return self.choice_text != ''		
		
	def contains_verylong_text(self):
		text_str = self.choice_text		
		return len(text_str) > 200		

survey/views.py
# Robin Kalia
# robinkalia@berkeley.edu
# UC Berkeley
#
# Views.py: Views that are mapped by the 'URLs' used in the 'Survey' Web Application


from django.http import HttpResponse, HttpResponseRedirect, Http404

from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse

from django.utils import timezone
from django.views import generic

from survey.models import Question, Choice


def index(request):
	""" index(): Manual Index View """
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	template = loader.get_template('survey/index.html')
	context = RequestContext(request, { 'latest_question_list' : latest_question_list})
	context2 = { 'latest_question_list' : latest_question_list }	
	list_response = '\n'.join([p.question for p in latest_question_list])
	response_init = "This is a simple Web App for Survey: \n\n"
	response = response_init + list_response
	# return HttpResponse(response)
	# return HttpResponse(template.render(context))
	return render(request, 'survey/index.html', context2)

class IndexView(generic.ListView):
	""" IndexView(): Generic Index View """
	template_name = 'survey/index.html'
	context_object_name = 'latest_question_list'	
	
	def get_queryset(self):
		#return Question.objects.order_by('-pub_date')[:5]
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


def detail(request, question_id):
	""" detail(): Manual Detail View """
	"""
	try:
		q = Question.objects.get(pk=question_id)
	except Question.DoesNotExist:
		raise Http404
	"""
	q = get_object_or_404(Question, pk=question_id)
	context = { 'question' : q }
	return render(request, 'survey/detail.html', context)

class DetailView(generic.DetailView):
	"""" DetailView(): Generic Detail View """
	model = Question
	template_name = 'survey/detail.html'


def vote(request, question_id):
	q = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = q.choice_set.get(pk=request.POST['choice'])
	except(KeyError, Choice.DoesNotExist):
		context = { 'question' : q, 'error_message' : "You didn't select a choice" } 
		return render(request, 'survey/detail.html', context)

	selected_choice.votes += 1
	selected_choice.save()
	return HttpResponseRedirect(reverse('survey:results', args=(q.id,)))


def results(request, question_id):
	q = get_object_or_404(Question, pk=question_id)
	context = {'question' : q}
	return render(request, 'survey/results.html', context)

class ResultsView(generic.DetailView):
	"""" DetailView(): Generic Results View """
	model = Question
	template_name = 'survey/results.html'

survey/templates/survey/detail.html
<!--
	Robin Kalia
	UC Berekeley
	robinkalia@berkeley.edu

	detail.html: The template for loading the details associated with the site/survey/<question_id> webpage
-->

<h1>{{question.id}}) {{ question.question }}:</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'survey:vote' question.id %}" method="post">
{% csrf_token %}

{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}"><h2>{{ choice.choice_text }}</h2>
{% endfor %}

<input type="submit" value="Vote" />
</form>

survey/templates/survey/index.html
<!--
	Robin Kalia
	UC Berekeley
	robinkalia@berkeley.edu

	index.html: The initial template that will be loaded for the site/survey/ webpage
-->

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'survey/style.css' %}" />

<p><h2>This is a simple Web App for Survey.</h2>Some of the latest Survey questions are mentioned below:</p>

{% if latest_question_list %}
	<ul>
	{% for q in latest_question_list %}
		<li><a href="{% url 'survey:detail' q.id %}">{{ q.question }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No Survey questions are available as of now.</p>
{% endif %}

survey/templates/survey/results.html
<!--
	Robin Kalia
	UC Berekeley
	robinkalia@berkeley.edu

	results.html: The template for displaying the results corresponding to a specific question (url: /survey/<question_id>)
-->

<h1>{{question.id}}) {{ question.question }}:</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li><h2>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}</h2></li>
{% endfor %}
</ul>

<a href="{% url 'survey:detail' question.id %}">Vote Again?</a>